package telas.projeto;

import dao.ProjetoDAO;
import entidades.Projeto;
import java.awt.event.ActionEvent;
import java.sql.SQLException;
import util.Mensagens;
import util.TamanhoFixo;

public class CadastroProjeto extends javax.swing.JDialog {

    private Projeto proj;
    private final ProjetoDAO projDao;

    public CadastroProjeto(java.awt.Frame parent, boolean modal, ProjetoDAO projDao) {
        super(parent, modal);

        this.projDao = projDao;

        initComponents();

        btSalvar.addActionListener(this::Salvar);

    }

    public CadastroProjeto(java.awt.Frame parent, boolean modal, ProjetoDAO projDao, Projeto proj) {
        super(parent, modal);

        this.proj = proj;

        this.projDao = projDao;

        initComponents();

        jcAtivo.setEnabled(true);

        btSalvar.addActionListener(this::alterar);

        btSalvar.setText("Alterar");

        preencherCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jcAtivo = new javax.swing.JCheckBox();
        txtNome = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        txtTtotalCaracteres = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nome:");

        jcAtivo.setSelected(true);
        jcAtivo.setText("Projeto Ativo");
        jcAtivo.setEnabled(false);

        txtNome.setDocument(new TamanhoFixo(60));
        txtNome.setDocument(new TamanhoFixo(60));
        txtNome.setToolTipText("No maxímo 60 caractere.");

        btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        btSalvar.setText("Salvar");

        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        jLabel4.setText("Descrição:");

        txtDescricao.setDocument(new TamanhoFixo(250));
        txtDescricao.setColumns(20);
        txtDescricao.setDocument(new TamanhoFixo(250));
        txtDescricao.setRows(5);
        txtDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescricaoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(txtDescricao);

        txtTtotalCaracteres.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTtotalCaracteres.setText("Total de caracteres: 0");
        txtTtotalCaracteres.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jcAtivo)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btCancelar))
                            .addComponent(txtTtotalCaracteres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jcAtivo))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTtotalCaracteres)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btSalvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void txtDescricaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescricaoKeyReleased
        txtTtotalCaracteres.setText("Total de caracteres: " + txtDescricao.getText().length());
    }//GEN-LAST:event_txtDescricaoKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jcAtivo;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNome;
    private javax.swing.JLabel txtTtotalCaracteres;
    // End of variables declaration//GEN-END:variables

    private void alterar(ActionEvent evt) {

        if (verificarCampos()) {

            try {

                popular();

                this.projDao.alterar(proj);

                Mensagens.sucesso();

                this.dispose();

            } catch (SQLException ex) {
                Mensagens.erro("Erro ao tentar Alterar: " + ex.getMessage());
            }

        }

    }

    private void Salvar(ActionEvent evt) {

        if (verificarCampos()) {

            this.proj = new Projeto();

            try {

                popular();

                this.projDao.salvar(proj);

                Mensagens.sucesso();

                this.dispose();

            } catch (SQLException ex) {
                Mensagens.erro("Erro ao tentar Salvar: " + ex.getMessage());
            }

        }

    }

    private boolean verificarCampos() {

        boolean conf = false;

        if (txtNome.getText().trim().isEmpty()) {
            Mensagens.atenção("O campo Nome é obrigatório.");
            txtNome.requestFocus();
        } else if (txtDescricao.getText().trim().isEmpty()) {
            Mensagens.atenção("O campo Descrição é obrigatório.");
            txtDescricao.requestFocus();
        } else {
            conf = true;
        }

        return conf;

    }

    private void popular() {

        this.proj.setNome(txtNome.getText().trim());
        this.proj.setDescricao(txtDescricao.getText());
        this.proj.setAtivo(jcAtivo.isSelected());

    }

    private void preencherCampos() {

        txtNome.setText(this.proj.getNome());
        txtDescricao.setText(this.proj.getDescricao());
        jcAtivo.setSelected(this.proj.isAtivo());

    }

}
